[package]
name = "offline"
version = "0.1.0"
edition = "2021"

[dependencies]

###################################
#           Bevy + sous-crates    #
###################################
# Crate Bevy principale (version crates.io)
bevy = "0.15.3"

